apiVersion: v1
kind: PersistentVolume
metadata:
     name: pv-elasticsearch-1
spec:
   storageClassName:  do-block-storage
   accessModes: 
      - ReadWriteOnce
   capacity:
         storage: 10Gi
   hostPath:
        path: /es-data-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
     name: pv-elasticsearch-2
spec:
   storageClassName:  do-block-storage     
   accessModes:
      - ReadWriteOnce
   capacity:
         storage: 10Gi
   hostPath:
        path: /es-data-2


---

apiVersion: v1
kind: PersistentVolume
metadata:
     name: pv-elasticsearch-3
spec:
   storageClassName:  do-block-storage     
   accessModes:
      - ReadWriteOnce
   capacity:
         storage: 10Gi
   hostPath:
        path: /es-data-3
